[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/oleksii/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *.internal
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[power caselight]
type: klipper_device
object_name: output_pin caselight

[file_manager]
enable_object_processing: True

[spoolman]
# server: http://192.168.88.241:7912
# server: https://spoolman.homelab.w16x.net
server: http://192.168.99.104

# BEGIN ANSIBLE MANAGED KLIPPAIN-SHAKETUNE UPDATE MANAGER
[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: /home/oleksii/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper
# END ANSIBLE MANAGED KLIPPAIN-SHAKETUNE UPDATE MANAGER

# BEGIN ANSIBLE MANAGED KAMP UPDATE MANAGER
[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main
# END ANSIBLE MANAGED KAMP UPDATE MANAGER

# BEGIN ANSIBLE MANAGED CARTOGRAPHER PLUGIN UPDATE MANAGER
[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin
# END ANSIBLE MANAGED CARTOGRAPHER PLUGIN UPDATE MANAGER

# BEGIN ANSIBLE MANAGED CARTOGRAPHER FIRMWARE UPDATE MANAGER
[update_manager Cartographer Firmware]
type: git_repo
path: ~/cartographer_firmware
is_system_service: False
origin: https://github.com/Cartographer3D/cartographer_firmware.git
primary_branch: main
# END ANSIBLE MANAGED CARTOGRAPHER FIRMWARE UPDATE MANAGER
